### ISSUE TITLE
Include libsodium from non-system path

### ISSUE THREAD

**Issue by ne0h** [stef/pysodium#26]
Hi,

I do not want to install libsodium and pysodium system-wide. Is it possible to include libsodium from a custom path? At the moment I get this error. I guess that libsodium is not found by pysodium.

```
['/Users/xxx/Projekte/catmail/client', '/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC', '/Library/Python/2.7/site-packages', '../3rdparty/pysodium-build/lib/python2.7/site-packages/pysodium-0.6.7-py2.7.egg']
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import pysodium
  File "build/bdist.macosx-10.11-intel/egg/pysodium/__init__.py", line 34, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, crypto_pwhash_scryptsalsa208sha256_strprefix): symbol not found
```

Thanks in advance!

**Comment by stef** [comment]
i dunno, that seems like an apple OS you're using, probably it has something like LD_LIBRARY_PATH or possibly LD_PRELOAD which you could use,
